name: Repo Sync

on:
  repository_dispatch:
    types: [source-merged]
  workflow_dispatch:
    inputs:
      sync_branch:
        description: 'Branch to sync'
        required: true
        default: 'main'
      dry_run:
        description: 'Perform a dry run?'
        required: false
        default: 'false'
      custom_message:
        description: 'Optional custom sync message'
        required: false

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: ${{ secrets.SOURCE_REPO }}
        source_branch: main
        destination_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        github_token: ${{ secrets.REPO_SYNC }}
        skip_if_no_changes: true
    - name: Print workflow inputs
      run: |
        echo "source_repo: ${{ inputs.source_repo }}"
        echo "destination_repository: ${{ inputs.destination_repository }}"
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        destination_repository: ${{ secrets.DESTINATION_REPOSITORY }}
        destination_branch: main
        github_token: ${{ secrets.REPO_SYNC }}
